In [28]:
from librosa.onset import onset_detect
import librosa
from madmom.audio.signal import SignalProcessor, FramedSignalProcessor
from madmom.audio.stft import ShortTimeFourierTransformProcessor
from madmom.audio.filters import MelFilterbank
from madmom.audio.spectrogram import (FilteredSpectrogramProcessor,
                                      LogarithmicSpectrogramProcessor)

In [2]:
import numpy as np
import joblib

with open("../data/dataset_features.npz", 'rb') as f:
    features = joblib.load(f)

In [1]:
import numpy as np
import joblib


with open("../data/multi_scaler_low.pkl", 'rb') as f:
    scaler_low = joblib.load(f)
    
with open("../data/multi_scaler_mid.pkl", 'rb') as f:
    scaler_mid = joblib.load(f)

with open("../data/multi_scaler_high.pkl", 'rb') as f:
    scaler_high = joblib.load(f)

In [104]:
with open("../data/scaler.pkl", 'rb') as f:
    scaler = joblib.load(f)

In [105]:
scaler.shape

(2, 15)

In [99]:
smaller[0]

array([[-2.795, -2.795, -2.795, ..., -3.94 , -3.83 , -4.383],
       [-2.178, -2.178, -2.178, ..., -2.309, -2.732, -3.71 ],
       [-1.505, -1.505, -1.505, ..., -2.562, -2.666, -3.379],
       ...,
       [-2.25 , -2.25 , -2.25 , ..., -1.868, -2.139, -2.31 ],
       [-2.176, -2.176, -2.176, ..., -1.824, -2.098, -2.229],
       [-2.3  , -2.3  , -2.3  , ..., -1.978, -2.21 , -2.23 ]],
      dtype=float16)

In [95]:
scaler_high

array([[1.2468907, 1.246283 , 1.2456695, 1.2450496, 1.2444187, 1.2437747,
        1.2431103, 1.2424166, 1.2417231, 1.2409903, 1.240241 , 1.2394862,
        1.2387303, 1.237972 , 1.237212 ],
       [1.2020398, 1.2019933, 1.2019464, 1.2018992, 1.2018511, 1.2018025,
        1.2017533, 1.2017033, 1.2016535, 1.2016041, 1.201555 , 1.2015066,
        1.2014589, 1.2014112, 1.2013618]], dtype=float32)

In [4]:
scaler_high

array([[1.2457175, 1.2454381, 1.2451525, 1.2448591, 1.2445551, 1.2442358,
        1.243894 , 1.2435199, 1.2431457, 1.2427292, 1.2422959, 1.2418566,
        1.2414157, 1.2409726, 1.2405264],
       [1.2137035, 1.2136649, 1.2136261, 1.2135873, 1.213548 , 1.2135079,
        1.2134669, 1.2134248, 1.2133831, 1.2133417, 1.2133007, 1.2132607,
        1.2132217, 1.2131823, 1.2131412]], dtype=float32)

In [96]:
scaler_mid

array([[0.8747069 , 0.8743256 , 0.8739377 , 0.8735424 , 0.8731342 ,
        0.8727016 , 0.8722207 , 0.8714114 , 0.87060237, 0.86975974,
        0.8687226 , 0.8676422 , 0.86655706, 0.8654679 , 0.8643751 ],
       [1.261682  , 1.261645  , 1.2616072 , 1.2615683 , 1.2615288 ,
        1.261488  , 1.2614461 , 1.2613953 , 1.2613449 , 1.2612914 ,
        1.2612319 , 1.2611731 , 1.2611145 , 1.2610564 , 1.2609992 ]],
      dtype=float32)

In [3]:
scaler_mid

array([[0.8752344 , 0.8751961 , 0.87515134, 0.8750988 , 0.8750322 ,
        0.87493896, 0.874792  , 0.8742899 , 0.87378836, 0.87324977,
        0.87250084, 0.87170494, 0.8709039 , 0.8700982 , 0.8692874 ],
       [1.2755594 , 1.2755313 , 1.2755029 , 1.2754737 , 1.275444  ,
        1.2754126 , 1.27538   , 1.2753378 , 1.2752957 , 1.2752507 ,
        1.2751988 , 1.2751479 , 1.2750971 , 1.2750461 , 1.2749965 ]],
      dtype=float32)

In [97]:
scaler_low

array([[0.53828776, 0.5379547 , 0.5376155 , 0.5372696 , 0.5369056 ,
        0.53650224, 0.5357637 , 0.53453934, 0.5333161 , 0.5320198 ,
        0.53071177, 0.5294139 , 0.5278753 , 0.5263299 , 0.5247849 ],
       [1.3225148 , 1.3224894 , 1.3224633 , 1.3224361 , 1.3224089 ,
        1.3223784 , 1.3223392 , 1.3222824 , 1.3222258 , 1.322157  ,
        1.322083  , 1.3220102 , 1.3219337 , 1.3218572 , 1.3217803 ]],
      dtype=float32)

In [2]:
scaler_low

array([[0.54078287, 0.5407952 , 0.5408004 , 0.5407974 , 0.5407762 ,
        0.54071033, 0.5402818 , 0.5393281 , 0.53837544, 0.53734213,
        0.53629726, 0.5352633 , 0.53396755, 0.53266263, 0.5313589 ],
       [1.3367289 , 1.3367143 , 1.3366988 , 1.3366826 , 1.3366666 ,
        1.3366474 , 1.3366194 , 1.3365719 , 1.336524  , 1.3364633 ,
        1.3363962 , 1.3363311 , 1.3362615 , 1.3361909 , 1.3361206 ]],
      dtype=float32)

In [100]:
scaler_mid.shape

(2, 15)

In [79]:
scaler_mid

array([[-0.1647, -0.1653, -0.1659, -0.1665, -0.1671, -0.1677, -0.1682,
        -0.1693, -0.1703, -0.1714, -0.1724, -0.1735, -0.1746, -0.1757,
        -0.1766],
       [ 0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756]], dtype=float16)

In [80]:
scaler_high

array([[0.07465, 0.07465, 0.0746 , 0.0746 , 0.0745 , 0.07446, 0.07446,
        0.0744 , 0.0743 , 0.0742 , 0.07416, 0.0741 , 0.07404, 0.0739 ,
        0.07385],
       [0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 ,
        0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 , 0.0756 ,
        0.0756 ]], dtype=float16)

In [76]:
scaler

array([[-0.1814, -0.1818, -0.182 , -0.1823, -0.1826, -0.1829, -0.1837,
        -0.1847, -0.1854, -0.1863, -0.1873, -0.1884, -0.1901, -0.191 ,
        -0.1924],
       [ 0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756]], dtype=float16)

In [74]:
scaler

array([[-0.1982, -0.1985, -0.1989, -0.199 , -0.1993, -0.1995, -0.2001,
        -0.201 , -0.2019, -0.2026, -0.2036, -0.2046, -0.2067, -0.2076,
        -0.2092],
       [ 0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,  0.0756,
         0.0756]], dtype=float16)

In [ ]:
small_f = features[10,:,:]

In [19]:
def feature_reshape(feature, multi=False):
    """
    reshape mfccBands feature into n_sample * n_row * n_col
    :param feature:
    :return:
    """

    n_sample = feature.shape[0]
    n_row = 80
    n_col = 15

    feature_reshaped = np.zeros((n_sample, n_row, n_col), dtype='float16')
    if multi:
        feature_reshaped = np.zeros((n_sample, n_row, n_col, feature.shape[-1]), dtype='float16')
    # print("reshaping feature...")
    for ii in range(n_sample):
        # print ii
        feature_frame = np.zeros((n_row, n_col), dtype='float16')
        if multi:
            feature_frame = np.zeros((n_row, n_col, feature.shape[-1]), dtype='float16')
        for jj in range(n_col):
            feature_frame[:, jj] = feature[ii][n_row * jj:n_row * (jj + 1)]
        feature_reshaped[ii, :, :] = feature_frame
    return feature_reshaped

In [24]:
np.var(features, axis = 1)

c:\users\mrchr\miniconda3\envs\tf2\lib\site-packages\numpy\core\_methods.py:199: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims)


array([1.437, 1.56 , 1.658, ..., 0.   , 0.   , 0.   ], dtype=float16)

In [38]:
def get_scalers():
    stds = np.mean(np.std(re_feat, axis = 0), axis = 0)
    means = np.mean(np.mean(re_feat, axis = 0), axis = 0)
    
%timeit get_scalers()

54.7 s ± 113 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
def get_scalers():
    stds = [np.std(re_feat[:,:,i]) for i in range(re_feat.shape[-1])]
    return stds
    #stds = np.mean(np.std(re_feat, axis = 0), axis = 0)
    #means = np.mean(np.mean(re_feat, axis = 0), axis = 0)
%timeit scalers = get_scalers()

37.8 s ± 437 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [46]:
from sklearn.preprocessing import scale

In [51]:
smaller = re_feat[:100]

In [63]:
[np.nanmean(np.nanstd(smaller, axis=1, keepdims = False), axis=0)].shape

(15,)

In [68]:
smaller = re_feat[:100000]
[np.nanmean(np.nanmean(smaller, axis=1), axis=0), np.nanmean(np.nanstd(smaller, axis=1), axis=0)]

[array([-0.1022 , -0.10223, -0.1023 , -0.1024 , -0.1025 , -0.10254,
        -0.10266, -0.1027 , -0.1028 , -0.1029 , -0.10297, -0.103  ,
        -0.10315, -0.1032 , -0.1033 ], dtype=float16),
 array([0.0819, 0.0819, 0.0819, 0.0819, 0.0819, 0.0819, 0.0819, 0.0819,
        0.0819, 0.0819, 0.0819, 0.0819, 0.0819, 0.0819, 0.0819],
       dtype=float16)]

In [52]:
scale(smaller, axis = 1)

ValueError: Found array with dim 3. the scale function expected <= 2.

In [45]:
scalers

[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]

In [42]:
len(scalers)

15

In [37]:
stds.shape, means.shape

((15,), (15,))

In [33]:
stds.shape

(1818016, 15)

In [22]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit(features)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
re_feat = feature_reshape(features)

In [27]:
re_feat.shape

(1818016, 80, 15)

In [1]:
import numpy as np
with open("training_data/dataset_features.npz", 'rb') as f:
    simple_f = np.load(f)['features']
labels = np.ones((len(simple_f),))

with open("training_data/sample_weights.npz", 'rb') as f:
    s_w = np.load(f)['sample_weights']
    
with open("training_data/extra_features.npz", 'rb') as f:
    e_f = np.load(f)['sample_weights']
    
import joblib
scalers = []

with open("training_data/scaler.pkl", 'rb') as f:
    scalers.append(joblib.load(f))

In [2]:
from training_scripts.timeseries_feature_generator import TimeFeatureGenerator
time_gen = TimeFeatureGenerator(simple_f,
                                np.ones((len(simple_f),)),
                                5,
                                256,
                                sample_weights=s_w,
                                extra_features=e_f,
                                scalers=scalers)

In [3]:
len(time_gen)

100

In [6]:
time_gen[0][2] 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [1]:
import numpy as np

limit = 1000000

with open("training_data/multi_dataset_features.npz", 'rb') as f:
    f_used = np.load(f)['features'][:limit]
    
with open("training_data/multi_labels.npz", 'rb') as f:
    labels = np.load(f)['labels'][:limit]
    
with open("training_data/multi_sample_weights.npz", 'rb') as f:
    s_w = np.load(f)['sample_weights'][:limit]
    
with open("training_data/multi_extra_features.npz", 'rb') as f:
    e_f = np.load(f)['extra_features'][:limit]
    
import joblib
scalers = []

with open("training_data/multi_scaler_low.pkl", "rb") as file:
    scalers.append(joblib.load(file))
with open("training_data/multi_scaler_mid.pkl", "rb") as file:
    scalers.append(joblib.load(file))
with open("training_data/multi_scaler_high.pkl", "rb") as file:
    scalers.append(joblib.load(file))

In [2]:
from training_scripts.timeseries_feature_generator import TimeFeatureGenerator
multi_time_gen = TimeFeatureGenerator(f_used,
                                labels,
                                5,
                                256,
                                sample_weights=s_w,
                                extra_features=e_f,
                                scalers=scalers,
                                     stride=2)

In [3]:
len(multi_time_gen)

3907

In [9]:
joblib.dump(multi_time_gen, "other_preprocessed_multi_generator.pkl")

['other_preprocessed_multi_generator.pkl']

In [25]:
len(multi_time_gen[])

7813

In [23]:
multi_time_gen[0][1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [8]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

In [17]:
gen = TimeseriesGenerator(snips, np.ones((snips.shape[0],)), 2, batch_size=10)

In [18]:
gen[0][0].shape

(10, 2, 80, 15, 3)

In [26]:
reshaped = f_used.reshape((f_used.shape[0], 80, 15, 3))

In [27]:
reshaped.shape

(2000000, 80, 15, 3)

In [28]:
snip = reshaped[0:256]

In [29]:
snip.shape

(256, 80, 15, 3)

In [33]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
gen = TimeseriesGenerator(snip, np.ones((snip.shape[0],5)), 5, batch_size=1)

In [36]:
gen[0][0].shape

(1, 5, 80, 15, 3)

In [34]:
len(gen)

251

In [31]:
len(gen) 30 * 3 + 60 * 5
         100ish + 150ish
    


7813

IndexError: too many indices for array

In [44]:
gen[0][1][:,1:3].shape

(256, 2)

In [35]:
gen[0][0].shape

(256, 5, 80, 15, 3)

In [52]:
def split_sequence(sequence, labels, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x = sequence[i:end_ix]
        y.append(labels[i])
        X.append(seq_x)
    return np.array(X), np.array(y)

In [43]:
first = f_used[0:20].reshape((20, 80, 15, 3))
first.shape

(20, 80, 15, 3)

In [53]:
splits, ys = split_sequence(first, labels, 5)

In [54]:
splits.shape, ys.shape

((15, 5, 80, 15, 3), (15,))

In [55]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [77]:
pad_seq = pad_sequences(splits,dtype='float16', padding='post', truncating='pre', value=0)
pad_seq.shape

(15, 5, 80, 15, 3)

In [72]:
pad_seq.shape

(15, 5, 80, 15, 3)

In [64]:
pad_seq[19]

array([[[ 0.5347 ,  1.286  ,  1.052  ],
        [ 1.019  ,  1.775  ,  2.58   ],
        [ 1.019  ,  1.506  ,  2.182  ],
        ...,
        [ 1.138  ,  1.556  ,  1.821  ],
        [ 0.7856 ,  1.158  ,  1.693  ],
        [ 1.01   ,  1.427  ,  1.715  ]],

       [[ 0.7666 ,  0.549  ,  1.075  ],
        [ 0.8193 ,  1.126  ,  1.525  ],
        [ 0.566  ,  1.173  ,  1.512  ],
        ...,
        [ 0.577  ,  0.551  ,  0.95   ],
        [ 0.564  ,  0.856  ,  1.071  ],
        [ 0.02481,  0.2073 ,  0.4988 ]],

       [[ 0.0711 ,  0.1838 ,  0.4197 ],
        [-0.05667, -0.0634 ,  0.2903 ],
        [-0.9517 , -0.3203 ,  0.2352 ],
        ...,
        [-1.409  , -1.097  , -0.844  ],
        [-1.226  , -0.9395 , -0.6025 ],
        [-1.601  , -1.32   , -0.8765 ]],

       ...,

       [[-1.026  , -0.6836 , -0.1588 ],
        [-1.425  , -1.133  , -0.442  ],
        [-0.8604 , -0.6284 , -0.1064 ],
        ...,
        [-1.926  , -1.412  , -0.8105 ],
        [-1.673  , -1.306  , -0.9653 ],
        [

In [2]:
import numpy as np

n_seq = 2
n_steps = 2
n_features = 1

x_input = np.array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, n_steps, n_features))

In [3]:
x_input

array([[[[60],
         [70]],

        [[80],
         [90]]]])

In [5]:

def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 4
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [6]:
X

array([[10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60],
       [40, 50, 60, 70],
       [50, 60, 70, 80]])

In [16]:
n_features = 1
n_seq = 4
n_steps = 1
X_new = X.reshape((X.shape[0], n_seq, n_steps, n_features))
X_new.shape

(5, 4, 1, 1)

In [9]:
y

array([50, 60, 70, 80, 90])

In [8]:
X_new

array([[[[10],
         [20]],

        [[30],
         [40]]],


       [[[20],
         [30]],

        [[40],
         [50]]],


       [[[30],
         [40]],

        [[50],
         [60]]],


       [[[40],
         [50]],

        [[60],
         [70]]],


       [[[50],
         [60]],

        [[70],
         [80]]]])

In [36]:
fs = 0.01
hopsize_t = 44100
proc = FramedSignalProcessor(frame_size=2048, hopsize=int(fs*hopsize_t))
frames = proc("testing_files/zombie_maker.wav")
frames.shape

(14887, 2048, 2)

In [38]:
fs = 0.01
hopsize_t = 44100
proc = FramedSignalProcessor(frame_size=1024, hopsize=int(fs*hopsize_t))
frames = proc("testing_files/zombie_maker.wav")
frames.shape

(14887, 1024, 2)

In [49]:
y, sr = librosa.load("testing_files/zombie_maker.wav", sr=44100)

In [51]:
onset_frames = librosa.onset.onset_detect(y=y, sr=sr, units="time", hop_length=int(sr*0.01))
onset_frames.shape

(466,)

In [59]:
onset_frames

array([  0.43,   0.65,   0.86,   1.08,   1.29,   1.51,   1.72,   1.93,
         2.15,   2.36,   2.58,   2.79,   3.  ,   3.22,   3.43,   3.65,
         3.86,   4.08,   4.29,   4.51,   4.72,   4.93,   5.15,   5.36,
         5.58,   5.79,   6.  ,   6.22,   6.43,   6.65,   6.86,   7.08,
         7.29,   7.51,   7.61,   7.72,   7.94,   8.15,   8.37,   8.58,
         8.79,   9.  ,   9.22,   9.43,   9.65,   9.76,   9.86,  10.08,
        10.19,  10.29,  10.51,  10.72,  10.94,  11.15,  11.36,  11.58,
        11.79,  12.01,  12.23,  12.33,  12.4 ,  12.65,  12.76,  12.97,
        13.18,  13.29,  13.5 ,  13.61,  13.72,  14.11,  14.15,  14.37,
        14.58,  14.79,  15.01,  15.23,  15.44,  15.65,  15.87,  16.08,
        16.29,  16.51,  16.72,  16.94,  17.15,  17.37,  17.58,  17.8 ,
        18.01,  18.22,  18.43,  18.65,  18.87,  19.08,  19.29,  19.51,
        19.72,  19.94,  20.15,  20.37,  20.58,  20.79,  21.01,  21.23,
        21.44,  21.65,  21.86,  22.08,  22.29,  22.51,  22.72,  22.94,
      

In [53]:
import madmom
proc = madmom.features.beats.DBNBeatTrackingProcessor(fps=100)
act = madmom.features.beats.RNNBeatProcessor()("testing_files/zombie_maker.wav")


In [65]:
proc = madmom.features.beats.DBNBeatTrackingProcessor(fps=100)


In [64]:
act = madmom.features.beats.RNNBeatProcessor()("testing_files/zombie_maker.wav")


In [54]:
beat_times = proc(act)

In [66]:
beat_times.shape

(347,)

In [60]:
from common.audio_preprocessing import get_madmom_log_mels

In [61]:
mfcc = get_madmom_log_mels("testing_files/zombie_maker.wav", 44100, 0.01, 1)

In [63]:
mfcc.shape

(14887, 1200)

In [67]:
onset_frames.shape

(466,)

In [69]:
hopsize_t

44100

In [2]:
import librosa
y, sr = librosa.load("C:/Users/mrchr/Documents/stepcovnet/data/wavs/yubisaki_chokoreto.wav")
librosa.beat.beat_track(y=y, sr=sr)

(143.5546875,
 array([  11,   28,   46,   64,   82,  100,  118,  136,  153,  171,  189,
         207,  225,  242,  260,  278,  296,  314,  332,  349,  367,  385,
         403,  421,  439,  456,  474,  492,  510,  527,  545,  563,  581,
         599,  617,  634,  652,  670,  688,  706,  724,  742,  759,  777,
         795,  812,  830,  848,  866,  884,  902,  919,  937,  955,  973,
         991, 1009, 1027, 1044, 1062, 1080, 1098, 1116, 1134, 1151, 1169,
        1187, 1205, 1223, 1240, 1258, 1276, 1294, 1312, 1329, 1347, 1365,
        1383, 1401, 1419, 1436, 1454, 1472, 1490, 1508, 1525, 1543, 1561,
        1579, 1597, 1615, 1633, 1650, 1668, 1686, 1704, 1722, 1740, 1757,
        1775, 1793, 1811, 1829, 1847, 1864, 1882, 1900, 1918, 1936, 1953,
        1971, 1989, 2007, 2025, 2042, 2060, 2078, 2096, 2114, 2132, 2149,
        2167, 2185, 2203, 2221, 2238, 2256, 2274, 2292, 2310, 2327, 2345,
        2363, 2381, 2399, 2417, 2435, 2453, 2470, 2488, 2506, 2524, 2541,
        2559, 2577, 2595