In [28]:
from librosa.onset import onset_detect
import librosa
from madmom.audio.signal import SignalProcessor, FramedSignalProcessor
from madmom.audio.stft import ShortTimeFourierTransformProcessor
from madmom.audio.filters import MelFilterbank
from madmom.audio.spectrogram import (FilteredSpectrogramProcessor,
                                      LogarithmicSpectrogramProcessor)

In [1]:
import numpy as np
with open("training_data/dataset_features.npz", 'rb') as f:
    simple_f = np.load(f)['features']
labels = np.ones((len(simple_f),))

with open("training_data/sample_weights.npz", 'rb') as f:
    s_w = np.load(f)['sample_weights']
    
with open("training_data/extra_features.npz", 'rb') as f:
    e_f = np.load(f)['sample_weights']
    
import joblib
scalers = []

with open("training_data/scaler.pkl", 'rb') as f:
    scalers.append(joblib.load(f))

In [2]:
from training_scripts.timeseries_feature_generator import TimeFeatureGenerator
time_gen = TimeFeatureGenerator(simple_f,
                                np.ones((len(simple_f),)),
                                5,
                                256,
                                sample_weights=s_w,
                                extra_features=e_f,
                                scalers=scalers)

In [3]:
len(time_gen)

100

In [6]:
time_gen[0][2] 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [1]:
import numpy as np

limit = 1000000

with open("training_data/multi_dataset_features.npz", 'rb') as f:
    f_used = np.load(f)['features'][:limit]
    
with open("training_data/multi_labels.npz", 'rb') as f:
    labels = np.load(f)['labels'][:limit]
    
with open("training_data/multi_sample_weights.npz", 'rb') as f:
    s_w = np.load(f)['sample_weights'][:limit]
    
with open("training_data/multi_extra_features.npz", 'rb') as f:
    e_f = np.load(f)['extra_features'][:limit]
    
import joblib
scalers = []

with open("training_data/multi_scaler_low.pkl", "rb") as file:
    scalers.append(joblib.load(file))
with open("training_data/multi_scaler_mid.pkl", "rb") as file:
    scalers.append(joblib.load(file))
with open("training_data/multi_scaler_high.pkl", "rb") as file:
    scalers.append(joblib.load(file))

In [2]:
from training_scripts.timeseries_feature_generator import TimeFeatureGenerator
multi_time_gen = TimeFeatureGenerator(f_used,
                                labels,
                                5,
                                256,
                                sample_weights=s_w,
                                extra_features=e_f,
                                scalers=scalers,
                                     stride=2)

In [3]:
len(multi_time_gen)

3907

In [9]:
joblib.dump(multi_time_gen, "other_preprocessed_multi_generator.pkl")

['other_preprocessed_multi_generator.pkl']

In [25]:
len(multi_time_gen[])

7813

In [23]:
multi_time_gen[0][1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [8]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

In [17]:
gen = TimeseriesGenerator(snips, np.ones((snips.shape[0],)), 2, batch_size=10)

In [18]:
gen[0][0].shape

(10, 2, 80, 15, 3)

In [26]:
reshaped = f_used.reshape((f_used.shape[0], 80, 15, 3))

In [27]:
reshaped.shape

(2000000, 80, 15, 3)

In [28]:
snip = reshaped[0:256]

In [29]:
snip.shape

(256, 80, 15, 3)

In [33]:
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
gen = TimeseriesGenerator(snip, np.ones((snip.shape[0],5)), 5, batch_size=1)

In [36]:
gen[0][0].shape

(1, 5, 80, 15, 3)

In [34]:
len(gen)

251

In [31]:
len(gen) 30 * 3 + 60 * 5
         100ish + 150ish
    


7813

IndexError: too many indices for array

In [44]:
gen[0][1][:,1:3].shape

(256, 2)

In [35]:
gen[0][0].shape

(256, 5, 80, 15, 3)

In [52]:
def split_sequence(sequence, labels, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x = sequence[i:end_ix]
        y.append(labels[i])
        X.append(seq_x)
    return np.array(X), np.array(y)

In [43]:
first = f_used[0:20].reshape((20, 80, 15, 3))
first.shape

(20, 80, 15, 3)

In [53]:
splits, ys = split_sequence(first, labels, 5)

In [54]:
splits.shape, ys.shape

((15, 5, 80, 15, 3), (15,))

In [55]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [77]:
pad_seq = pad_sequences(splits,dtype='float16', padding='post', truncating='pre', value=0)
pad_seq.shape

(15, 5, 80, 15, 3)

In [72]:
pad_seq.shape

(15, 5, 80, 15, 3)

In [64]:
pad_seq[19]

array([[[ 0.5347 ,  1.286  ,  1.052  ],
        [ 1.019  ,  1.775  ,  2.58   ],
        [ 1.019  ,  1.506  ,  2.182  ],
        ...,
        [ 1.138  ,  1.556  ,  1.821  ],
        [ 0.7856 ,  1.158  ,  1.693  ],
        [ 1.01   ,  1.427  ,  1.715  ]],

       [[ 0.7666 ,  0.549  ,  1.075  ],
        [ 0.8193 ,  1.126  ,  1.525  ],
        [ 0.566  ,  1.173  ,  1.512  ],
        ...,
        [ 0.577  ,  0.551  ,  0.95   ],
        [ 0.564  ,  0.856  ,  1.071  ],
        [ 0.02481,  0.2073 ,  0.4988 ]],

       [[ 0.0711 ,  0.1838 ,  0.4197 ],
        [-0.05667, -0.0634 ,  0.2903 ],
        [-0.9517 , -0.3203 ,  0.2352 ],
        ...,
        [-1.409  , -1.097  , -0.844  ],
        [-1.226  , -0.9395 , -0.6025 ],
        [-1.601  , -1.32   , -0.8765 ]],

       ...,

       [[-1.026  , -0.6836 , -0.1588 ],
        [-1.425  , -1.133  , -0.442  ],
        [-0.8604 , -0.6284 , -0.1064 ],
        ...,
        [-1.926  , -1.412  , -0.8105 ],
        [-1.673  , -1.306  , -0.9653 ],
        [

In [2]:
import numpy as np

n_seq = 2
n_steps = 2
n_features = 1

x_input = np.array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, n_steps, n_features))

In [3]:
x_input

array([[[[60],
         [70]],

        [[80],
         [90]]]])

In [5]:

def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 4
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [6]:
X

array([[10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60],
       [40, 50, 60, 70],
       [50, 60, 70, 80]])

In [16]:
n_features = 1
n_seq = 4
n_steps = 1
X_new = X.reshape((X.shape[0], n_seq, n_steps, n_features))
X_new.shape

(5, 4, 1, 1)

In [9]:
y

array([50, 60, 70, 80, 90])

In [8]:
X_new

array([[[[10],
         [20]],

        [[30],
         [40]]],


       [[[20],
         [30]],

        [[40],
         [50]]],


       [[[30],
         [40]],

        [[50],
         [60]]],


       [[[40],
         [50]],

        [[60],
         [70]]],


       [[[50],
         [60]],

        [[70],
         [80]]]])

In [36]:
fs = 0.01
hopsize_t = 44100
proc = FramedSignalProcessor(frame_size=2048, hopsize=int(fs*hopsize_t))
frames = proc("testing_files/zombie_maker.wav")
frames.shape

(14887, 2048, 2)

In [38]:
fs = 0.01
hopsize_t = 44100
proc = FramedSignalProcessor(frame_size=1024, hopsize=int(fs*hopsize_t))
frames = proc("testing_files/zombie_maker.wav")
frames.shape

(14887, 1024, 2)

In [49]:
y, sr = librosa.load("testing_files/zombie_maker.wav", sr=44100)

In [51]:
onset_frames = librosa.onset.onset_detect(y=y, sr=sr, units="time", hop_length=int(sr*0.01))
onset_frames.shape

(466,)

In [59]:
onset_frames

array([  0.43,   0.65,   0.86,   1.08,   1.29,   1.51,   1.72,   1.93,
         2.15,   2.36,   2.58,   2.79,   3.  ,   3.22,   3.43,   3.65,
         3.86,   4.08,   4.29,   4.51,   4.72,   4.93,   5.15,   5.36,
         5.58,   5.79,   6.  ,   6.22,   6.43,   6.65,   6.86,   7.08,
         7.29,   7.51,   7.61,   7.72,   7.94,   8.15,   8.37,   8.58,
         8.79,   9.  ,   9.22,   9.43,   9.65,   9.76,   9.86,  10.08,
        10.19,  10.29,  10.51,  10.72,  10.94,  11.15,  11.36,  11.58,
        11.79,  12.01,  12.23,  12.33,  12.4 ,  12.65,  12.76,  12.97,
        13.18,  13.29,  13.5 ,  13.61,  13.72,  14.11,  14.15,  14.37,
        14.58,  14.79,  15.01,  15.23,  15.44,  15.65,  15.87,  16.08,
        16.29,  16.51,  16.72,  16.94,  17.15,  17.37,  17.58,  17.8 ,
        18.01,  18.22,  18.43,  18.65,  18.87,  19.08,  19.29,  19.51,
        19.72,  19.94,  20.15,  20.37,  20.58,  20.79,  21.01,  21.23,
        21.44,  21.65,  21.86,  22.08,  22.29,  22.51,  22.72,  22.94,
      

In [53]:
import madmom
proc = madmom.features.beats.DBNBeatTrackingProcessor(fps=100)
act = madmom.features.beats.RNNBeatProcessor()("testing_files/zombie_maker.wav")


In [65]:
proc = madmom.features.beats.DBNBeatTrackingProcessor(fps=100)


In [64]:
act = madmom.features.beats.RNNBeatProcessor()("testing_files/zombie_maker.wav")


In [54]:
beat_times = proc(act)

In [66]:
beat_times.shape

(347,)

In [60]:
from common.audio_preprocessing import get_madmom_log_mels

In [61]:
mfcc = get_madmom_log_mels("testing_files/zombie_maker.wav", 44100, 0.01, 1)

In [63]:
mfcc.shape

(14887, 1200)

In [67]:
onset_frames.shape

(466,)

In [69]:
hopsize_t

44100